// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0SapdzXPOhDPjlmm6RQMChAmRzjp1bLc',
    appId: '1:1082113274127:web:3e6658cc8202931beb4e7a',
    messagingSenderId: '1082113274127',
    projectId: 'fir-3-95cee',
    authDomain: 'fir-3-95cee.firebaseapp.com',
    storageBucket: 'fir-3-95cee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUiW3MEsyyxcgmMXARIp0dqT1NNRpd8Rs',
    appId: '1:1082113274127:android:54be5b5b31155e9deb4e7a',
    messagingSenderId: '1082113274127',
    projectId: 'fir-3-95cee',
    storageBucket: 'fir-3-95cee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeUDinl2LB37j7ViVoFpRePC5761XmQVk',
    appId: '1:1082113274127:ios:6f06b9f704d95328eb4e7a',
    messagingSenderId: '1082113274127',
    projectId: 'fir-3-95cee',
    storageBucket: 'fir-3-95cee.appspot.com',
    iosBundleId: 'com.example.firebase3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeUDinl2LB37j7ViVoFpRePC5761XmQVk',
    appId: '1:1082113274127:ios:e469995e858eee34eb4e7a',
    messagingSenderId: '1082113274127',
    projectId: 'fir-3-95cee',
    storageBucket: 'fir-3-95cee.appspot.com',
    iosBundleId: 'com.example.firebase3.RunnerTests',
  );
}
